using Volo.Abp;

namespace ConsumeAbpFromXamarinAppAPI.EntityFrameworkCore;

public abstract class ConsumeAbpFromXamarinAppAPIEntityFrameworkCoreTestBase : ConsumeAbpFromXamarinAppAPITestBase<ConsumeAbpFromXamarinAppAPIEntityFrameworkCoreTestModule>
{

}
