namespace ConsumeAbpFromXamarinAppAPI;

public abstract class ConsumeAbpFromXamarinAppAPIApplicationTestBase : ConsumeAbpFromXamarinAppAPITestBase<ConsumeAbpFromXamarinAppAPIApplicationTestModule>
{

}
