using Volo.Abp;

namespace ConsumeAbpFromXamarinApp.EntityFrameworkCore;

public abstract class ConsumeAbpFromXamarinAppEntityFrameworkCoreTestBase : ConsumeAbpFromXamarinAppTestBase<ConsumeAbpFromXamarinAppEntityFrameworkCoreTestModule>
{

}
